name: arwild
sdf: False
training:
  gpus: [3]
  test_gpus: [3]
  thresh: 0.5
  only_mlp_param: False
  image_encoder_path: 'checkpoints/net_G'
dataset:
  overfit: False
  input_im: 'rgb'
  aug: False
net:
  geometric_init: False
  ctype: 'canon_point'
  point_feat_dim: 3
  num_stack: 1
  loss_type: ['occ']

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True # if True, will remove floating pieces