name: arch
sdf: False
training:
  gpus: [2]
  test_gpus: [2]
  thresh: 0.5
net:
  geometric_init: False
  geo_feat_dict: {'canon': ['joints']}
  point_feat_dim: 72
  loss_type: ['occ']
  use_filter: True
  use_normal: False

# user defined
mcube_res: 256    # occupancy field resolution, higher --> more details
clean_mesh: True # if True, will remove floating pieces